### ISSUE TITLE
Add set definition from Hiera

### ISSUE THREAD

**Issue by LionelCons** [duritong/puppet-nftables#24]
Currently, rules can be defined in Hiera. This is very good.

The same should be done for sets, for symmetry purposes and to be able to define in Hiera rules that depend on sets.

It seems that the following addition to `init.pp` should be enough:
```
  $sets.each |$n,$v| {
    nftables::set{
      $n:
        * => $v
    }
  }

```

**Comment by nbarrientos** [comment]
I could implement this but I'd personally actually do the opposite. I'd remove `nftables::rules` (the parameter). Users wanting to provide rules or sets via Hiera can do so today by using [`create_resources()`](https://puppet.com/docs/puppet/6.19/function.html#create_resources)

**Comment by duritong** [comment]
create_resources was a workaround for what @LionelCons proposes back in the day when the splat operator did not yet exist.
It comes with multiple problems. E.g. no linenumber and manifests file reference where it was created and thus problems with such resources are hard to debug.

Since the language has loops and the splat operator, this is the way to go. Also how can they create resource with `create_resources()` when it nobody calls that function (in this module).

**Comment by nbarrientos** [comment]
Ok by me. Will wait until the patch queue clears out a bit to send something.
